apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: utrains-argo-app1
spec:
  project: default
  source:
    repoURL: https://github.com/utrains/argocd-app-config.git
    targetRevision: HEAD
    path: qa
  destination:
    server: https://kubernetes.default.svc
    namespace: myapp
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: utrains-app-deployment
  namespace: myapp
spec:
  replicas: 4
  selector:
    matchLabels:
      app: utrains-app
  template:
    metadata:
      labels:
        app: utrains-app
    spec:
      containers:
      - name: utrains-app-container
        image: your-docker-image:latest
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: utrains-app-hpa
  namespace: myapp
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: utrains-app-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
