apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: utrains-argo-app1
  namespace: qa
spec:
  project: default
  source:
    repoURL: https://github.com/utrains/argocd-app-config.git
    targetRevision: HEAD
    path: qa
  destination:
    server: https://kubernetes.default.svc
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
